debug: false

local:
  address: "localhost"
  port: "8080"

prod:
  address: "81.200.149.16"
  port: "8080"

test_db:
  host: "localhost"
  port: "5432"
  user: "postgres"
  pass: "postgres"
  name: "MakeTest"

prod_db:
  host: "147.45.144.230"
  port: "5432"
  name: "default_db"