address: "localhost"
port: "8080"

debug: false

test_db:
  host: "localhost"
  port: "5432"
  user: "postgres"
  pass: "postgres"
  name: "MakeTest"

prod_db:
  host: "147.45.144.230"
  port: "5432"
  name: "default_db"